set(EXPECTED_BM2DX_PRODUCT_VERSION                     "2025021200")

set(EXPECTED_BM2DX_NT_CODE_SIZE                        0x03bede00)
set(EXPECTED_BM2DX_NT_ENTRYPOINT                       0x03bf2020)
set(EXPECTED_BM2DX_NT_IMAGE_SIZE                       0x03c50000)

set(RESOLVED_DEATH_DEFYING_PATCH                       0x001ebd3f)
set(RESOLVED_STATE_PTR                                 0x026a25f0)
set(RESOLVED_GAUGE_DATA_PTR                            0x005999f8)
set(RESOLVED_GRAPH_DATA_PTR                            0x00599a4a)
set(RESOLVED_OPTION_DATA_PTR                           0x01acf338)
set(RESOLVED_INPUT_PTR                                 0x026418c8)
set(RESOLVED_STAGE_GAME_DATA                           0x01acf3a0)
set(RESOLVED_P1_GROOVE_GAUGE_PTR                       0x02aaaad0)
set(RESOLVED_P2_GROOVE_GAUGE_PTR                       0x02aaaada)
set(RESOLVED_P1_CHART_JUDGEMENT_PTR                    0x02aaaad2)
set(RESOLVED_P2_CHART_JUDGEMENT_PTR                    0x02aaaadc)
set(RESOLVED_P1_GAUGE_OPTION_PTR                       0x01acf128)
set(RESOLVED_P2_GAUGE_OPTION_PTR                       0x01acf15c)
set(RESOLVED_P1_DEAD_MEASURE_PTR                       0x01d7bf9c)
set(RESOLVED_P2_DEAD_MEASURE_PTR                       0x01d7bfa0)
set(RESOLVED_CALCULATE_INDIVIDUAL_CHART_JUDGE_VALUE    0x001eb920)
set(RESOLVED_TARGET_CALCULATE_CHART_JUDGE              0x0011aa10)
set(RESOLVED_TARGET_UPDATE_GROOVE_GAUGE                0x001ebbc0)
set(RESOLVED_TARGET_UPDATE_GRAPH_DATA                  0x001ec0ea)
set(RESOLVED_TARGET_STAGE_RESULT_CTOR                  0x0017e200)
set(RESOLVED_TARGET_RESULT_GRAPH_RENDER                0x0017acc0)
set(RESOLVED_TARGET_RETURN_FROM_RESULT                 0x0017f030)