name: Build (MSYS2 CLANG64)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: CLANG64
          update: true
          install: mingw-w64-clang-x86_64-ninja mingw-w64-clang-x86_64-clang mingw-w64-clang-x86_64-cmake mingw-w64-clang-x86_64-safetyhook mingw-w64-clang-x86_64-spdlog git

      - name: Configure CMake
        run: |
          cmake -S . -B build/ \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build with CMake
        run: |
          cmake --build build/ --config Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: build/2dx-gsm.dll