name: Build (LLVM)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11

      - name: Cache vcpkg binaries
        uses: actions/cache@v4
        with:
          path: C:\vcpkg-cache
          key: vcpkg-llvm-${{ hashFiles('vcpkg.json') }}

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: CLANG64
          update: true
          install: mingw-w64-clang-x86_64-ninja mingw-w64-clang-x86_64-toolchain mingw-w64-clang-x86_64-cmake git

      - name: Get commit hash
        id: vars
        run: echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Configure CMake
        run: |
          cmake -S . -B build/ \
            -DVCPKG_TARGET_TRIPLET=x64-mingw-static \
            -DVCPKG_HOST_TRIPLET=x64-mingw-static \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_TOOLCHAIN_FILE="vcpkg/scripts/buildsystems/vcpkg.cmake" \
            -DCMAKE_SHARED_LINKER_FLAGS="-static -static-libstdc++ -s"
        env:
          VCPKG_BINARY_SOURCES: "clear;files,C:/vcpkg-cache,readwrite"

      - name: Build with CMake
        run: |
          cmake --build build/ --config Release

      - name: Prepare artifact
        run: |
          mkdir -v artifact/
          cp -v build/2dx-gsm.dll artifact/
          cp -v dist/2dx-gsm.ini artifact/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 2dx-gsm-${{ steps.vars.outputs.commit_hash }}-llvm
          path: artifact/